import type { Publication, Question, StudyProfile } from "@/domain/types";

const source = (section: string, page: number, excerpt: string) => ({ publicationId: "aoh", publicationTitle: "C-146A Aircraft Operating Handbook", section, page, excerpt });
export const publications: Publication[] = [
  { id: "aoh", title: "C-146A Aircraft Operating Handbook", platform: "C-146A", category: "systems", enabled: true, dailyQuiz: true, dailyLesson: true, priority: "high", sensitivity: "private", status: "ready", pages: 412 },
  { id: "weather", title: "Aviation Weather Handbook", platform: "General Aviation", category: "weather", enabled: true, dailyQuiz: true, dailyLesson: true, priority: "normal", sensitivity: "public", status: "ready", pages: 583 },
  { id: "vol3", title: "AFMAN 11-202 Volume 3", platform: "Air Force Aviation", category: "regulations", enabled: false, dailyQuiz: false, dailyLesson: false, priority: "normal", sensitivity: "private", status: "ready", pages: 226 }
];
export const questions: Question[] = [
  { id: "q1", type: "multiple-choice", prompt: "Which indication best confirms that the standby electrical source is supplying the essential bus?", choices: ["Essential-bus voltage is present", "Both generators show normal load", "Fuel transfer begins", "Cabin pressure increases"], answer: "Essential-bus voltage is present", explanation: "The essential-bus indication verifies that the alternate source is reaching the equipment that remains powered.", category: "systems", criticality: 0.9, source: source("Electrical System — Standby Power", 87, "The standby source supplies the essential bus when the primary source is unavailable.") },
  { id: "q2", type: "scenario", prompt: "During climb, you observe a steady rise in oil temperature with falling pressure. What is the most appropriate immediate priority?", choices: ["Continue to destination", "Reduce power and land as soon as practical", "Cycle the alternator", "Increase airspeed only"], answer: "Reduce power and land as soon as practical", explanation: "The combination indicates a possible lubrication problem. Reducing power limits stress while you select a suitable landing location.", category: "emergency", criticality: 1, source: source("Engine Malfunctions", 196, "Abnormal oil pressure or temperature requires prompt evaluation and landing action.") },
  { id: "q3", type: "exact-recall", prompt: "Complete the limitation: Maximum demonstrated crosswind component is ___ knots.", answer: "25", explanation: "This is an exact numerical limitation. Recheck the published limitation before operational use.", category: "limitations", criticality: 0.95, strictRecall: true, source: source("Limitations", 34, "Maximum demonstrated crosswind component: 25 knots.") },
  { id: "q4", type: "multiple-choice", prompt: "A METAR reports visibility as 1 1/2SM. What does this describe?", choices: ["Prevailing horizontal visibility", "Cloud-base height", "Runway visual range", "Ceiling at the destination"], answer: "Prevailing horizontal visibility", explanation: "METAR visibility is the prevailing horizontal visibility reported at the station.", category: "weather", criticality: 0.5, isNew: true, source: { publicationId: "weather", publicationTitle: "Aviation Weather Handbook", section: "METARs", page: 54, excerpt: "Visibility is reported in statute miles and fractions of statute miles." } },
  { id: "q5", type: "free-recall", prompt: "Why does a published maximum demonstrated crosswind value matter during preflight decision-making?", answer: "It informs risk assessment and aircraft control margins", explanation: "It is a tested reference point that should inform, rather than replace, a full operational risk assessment.", category: "limitations", criticality: 0.7, source: source("Limitations", 34, "Maximum demonstrated crosswind component: 25 knots.") }
];
export const profiles: StudyProfile[] = [{ id: "current", name: "Current Aircraft", description: "Core aircraft and operational knowledge", questionCount: 5, emphasis: ["systems", "emergency", "limitations"] }, { id: "checkride", name: "Checkride Prep", description: "More critical items and weak areas", questionCount: 10, emphasis: ["limitations", "emergency"] }];
