"use client";

import { useEffect, useMemo, useState } from "react";
import { publications, questions } from "@/services/demo-data";
import { selectDailyQuestions } from "@/domain/study";
import type { Question } from "@/domain/types";

type Tab = "Today" | "Study" | "Library" | "Progress" | "Settings";
const nav: { label: Tab; icon: string }[] = [{ label: "Today", icon: "⌂" }, { label: "Study", icon: "◫" }, { label: "Library", icon: "▤" }, { label: "Progress", icon: "◔" }, { label: "Settings", icon: "⚙" }];

function Source({ question }: { question: Question }) { const s = question.source; return <div className="source"><span>↗</span><div><b>{s.publicationTitle}</b><small>{s.section} · p. {s.page}</small></div><button className="source-link" onClick={() => alert(s.excerpt)}>View source</button></div>; }

function Today({ start }: { start: () => void }) { return <>
  <section className="hero"><p className="eyebrow">SUNDAY, SEPTEMBER 6</p><h1>Good morning, Alex.</h1><p className="muted">A little recurrent practice goes a long way.</p><div className="session-card"><div className="ring"><span>5</span><small>min</small></div><div><p className="eyebrow">TODAY&apos;S RECURRENT</p><h2>Ready when you are</h2><p className="muted">5 questions · 1 new concept</p></div><button className="round" onClick={start}>→</button></div><button className="primary full" onClick={start}>Start session <span>→</span></button></section>
  <section className="section-head"><div><p className="eyebrow">LEARN SOMETHING NEW</p><h2>What METAR visibility really tells you</h2></div><span className="minutes">2 min</span></section>
  <article className="lesson"><p>A METAR&apos;s visibility is the <b>prevailing horizontal visibility</b> at the reporting station. It&apos;s a snapshot—use it with trends, forecasts, and what you observe.</p><div className="takeaway"><span>✦</span><div><b>Key takeaway</b><p>Reported visibility is one data point, not a complete go/no-go answer.</p></div></div><div className="citation">Aviation Weather Handbook · METARs · p. 54</div><button className="text-button" onClick={start}>Quick check <span>→</span></button></article>
  <section className="snapshot"><div><p className="eyebrow">YOUR MOMENTUM</p><h3>4 day streak <span>↗</span></h3><p className="muted">You&apos;re building a strong review rhythm.</p></div><div className="streak">● ● ● ● <i>●</i> <i>●</i> <i>●</i></div></section>
</>; }

function Study({ onFinish }: { onFinish: () => void }) { const session = useMemo(() => selectDailyQuestions(questions, {}, 5), []); const [index, setIndex] = useState(0); const [choice, setChoice] = useState(""); const [revealed, setRevealed] = useState(false); const q = session[index]; const correct = choice.trim().toLowerCase() === q.answer.toLowerCase();
  const advance = () => { if (index === session.length - 1) onFinish(); else { setIndex(index + 1); setChoice(""); setRevealed(false); } };
  return <section className="study-view"><div className="study-top"><button className="back" onClick={onFinish}>←</button><span>Daily session</span><span>{index + 1} of {session.length}</span></div><div className="progress-line"><i style={{ width: `${((index + 1) / session.length) * 100}%` }} /></div><p className="tag">{q.type.replace("-", " ")}</p><h1>{q.prompt}</h1>{q.choices ? <div className="answers">{q.choices.map(answer => <button key={answer} className={revealed ? answer === q.answer ? "correct" : answer === choice ? "incorrect" : "" : choice === answer ? "selected" : ""} onClick={() => !revealed && setChoice(answer)}>{answer}<span>{revealed && answer === q.answer ? "✓" : ""}</span></button>)}</div> : <textarea placeholder={q.strictRecall ? "Enter exact value" : "Type your response"} value={choice} onChange={e => setChoice(e.target.value)} />}{!revealed ? <button disabled={!choice.trim()} className="primary full submit" onClick={() => setRevealed(true)}>Check answer</button> : <div className="feedback"><p className={correct ? "good" : "needs-work"}>{correct ? "Correct" : "Review this one"}</p><p>{q.explanation}</p><Source question={q} /><button className="primary full" onClick={advance}>{index === session.length - 1 ? "Finish session" : "Next question"} <span>→</span></button></div>}</section> }

function Library() { const [items, setItems] = useState(publications); return <section><div className="screen-title"><div><p className="eyebrow">SOURCE LIBRARY</p><h1>Your publications</h1></div><button className="upload" onClick={() => alert("PDF upload is wired for Firebase Storage in production. Configure Firebase to enable it.")}>＋ Upload</button></div><p className="muted intro">Only active publications contribute new material. Your history is always retained.</p><div className="library-list">{items.map((p, index) => <article className="publication" key={p.id}><div className="pub-icon">▤</div><div className="pub-copy"><h3>{p.title}</h3><p>{p.platform} · {p.pages} pages</p><span className={p.status}>{p.status}</span></div><label className="toggle"><input type="checkbox" checked={p.enabled} onChange={() => setItems(current => current.map((x, i) => i === index ? { ...x, enabled: !x.enabled, dailyQuiz: !x.enabled } : x))} /><i /></label></article>)}</div><article className="sensitivity"><span>◇</span><div><b>Handle source material responsibly</b><p>Only upload publications you&apos;re authorized to store and process. Controlled material is never sent to external AI.</p></div></article></section>; }

function Progress() { const topics = [["Aircraft systems", 85], ["Emergency procedures", 90], ["Limitations", 75], ["Weather", 70]]; return <section><div className="screen-title"><div><p className="eyebrow">PROFICIENCY</p><h1>Progress that matters</h1></div></div><article className="backlog"><div><p className="eyebrow">REVIEW BACKLOG</p><h2>3 items due</h2><p className="muted">A short review now keeps them fresh.</p></div><button className="round">→</button></article><h2 className="subhead">Topic confidence</h2><p className="muted small">Based on recall history. Scores round to avoid false precision.</p><div className="topics">{topics.map(([name, pct]) => <div key={name as string}><div><b>{name}</b><span>{pct}%</span></div><i><em style={{ width: `${pct}%` }} /></i></div>)}</div><article className="weekly"><p className="eyebrow">LAST 7 DAYS</p><h2>18 minutes studied</h2><div className="bars"><i /><i /><i /><i /><i /><i /><i /></div></article></section>; }

function Settings() { return <section><div className="screen-title"><div><p className="eyebrow">PREFERENCES</p><h1>Settings</h1></div></div><div className="setting-group"><p className="eyebrow">STUDY</p>{[["Daily session", "5 minutes"], ["Active profile", "Current Aircraft"], ["Question preference", "Mixed recall"]].map(([a,b]) => <button key={a}><span>{a}<small>{b}</small></span><i>›</i></button>)}</div><div className="setting-group"><p className="eyebrow">ACCOUNT & DATA</p>{[["Device preferences", "This iPhone"], ["Privacy & source data", "Manage data"], ["Sign out", ""]].map(([a,b]) => <button key={a}><span>{a}<small>{b}</small></span><i>›</i></button>)}</div></section>; }

export default function Home() { const [tab, setTab] = useState<Tab>("Today"); const [studying, setStudying] = useState(false); const [done, setDone] = useState(false); useEffect(() => { if ("serviceWorker" in navigator) navigator.serviceWorker.register("/sw.js"); }, []); const start = () => setStudying(true); const finish = () => { setStudying(false); setDone(true); setTab("Today"); }; if (studying) return <main className="app"><Study onFinish={finish} /></main>; return <main className="app"><div className="topbar"><div className="mark">R</div><span>RECURRENT</span><button aria-label="Notifications">◌</button></div><div className="content">{done && <div className="toast">Today&apos;s session complete. Tomorrow&apos;s review has been adjusted.</div>}{tab === "Today" && <Today start={start} />}{tab === "Study" && <section className="study-menu"><p className="eyebrow">STUDY</p><h1>Choose your focus</h1>{["Daily Session", "Quick Quiz", "Emergency Procedures", "Limitations", "Weak Areas"].map((x, i) => <button key={x} onClick={start}><span className="menu-icon">{["◉", "◫", "!", "⌁", "◔"][i]}</span><span><b>{x}</b><small>{i === 0 ? "5 questions · 5 minutes" : "Targeted review"}</small></span><i>›</i></button>)}</section>}{tab === "Library" && <Library />}{tab === "Progress" && <Progress />}{tab === "Settings" && <Settings />}</div><nav>{nav.map(item => <button key={item.label} className={tab === item.label ? "active" : ""} onClick={() => setTab(item.label)}><span>{item.icon}</span>{item.label}</button>)}</nav></main>; }
